# -*- coding: utf-8 -*-
"""DecisionTree1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jAT3_HrwacnJv0n2FpJFszZXJlRrDUiz
"""

import pandas as pd
df = pd.read_csv('/content/Grade1.csv')
df

x = df.iloc[:,3:9]
x

x = df.iloc[:,3:9]
x

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)

from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()  
x_train= st_x.fit_transform(x_train)    
x_test= st_x.transform(x_test)

from sklearn.tree import DecisionTreeClassifier  
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)  
classifier.fit(x_train, y_train)

#Predicting the test set result  
y_pred= classifier.predict(x_test)  
y_pred

pd.DataFrame({'Actual':y_test,'Pred':y_pred})

#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(y_test, y_pred)  
cm

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)